#    This file is part of darktable.
#    copyright (c) 2016 Roman Lebedev.
#
#    darktable is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    darktable is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with darktable.  If not, see <http://www.gnu.org/licenses/>.

#Removed Linux versions - trying to get a working OSX build


language: generic

os:
  - osx

osx_image: xcode8.1

sudo: required

services:
  - docker

before_install:
    #  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew tap Homebrew/bundle && brew bundle --verbose; fi
    - brew update
    - brew tap Homebrew/bundle 
    - rm /usr/local/include/c++
    - brew bundle --verbose

env:
  global:
    - SRC_DIR=/build/darktable
    - BUILD_DIR=/build/darktable-build
    - INSTALL_PREFIX=/build/darktable-install
    - CFLAGS=-pipe CXXFLAGS=-pipe
    - CC=gcc-6 CXX=c++ TARGET=build # can't use CXX=g++-6 fails for osx.mm
#  fast_finish: true
#  matrix:
#    - CC=cc CXX=c++ TARGET=build # default system compiler, all platforms

#matrix:
#  fast_finish: true
#  include:
#  - os: osx
#    env: CC=gcc-6 CXX=c++ TARGET=build # can't use CXX=g++-6 fails for osx.mm

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      export SRC_DIR="$TRAVIS_BUILD_DIR";
      export BUILD_DIR="$SRC_DIR/build";
      export INSTALL_PREFIX="$SRC_DIR/install";
      mkdir "$BUILD_DIR";
      mkdir "$INSTALL_PREFIX";
      "$SRC_DIR/ci-script.sh";
    fi

after_success:
    - cd "$SRC_DIR"
    - pwd
    - ls
    - curl -O http://ftp.gnome.org/pub/gnome/sources/gtk-mac-bundler/0.7/gtk-mac-bundler-0.7.4.tar.xz
    - tar -xf gtk-mac-bundler-0.7.4.tar.xz
    - cd gtk-mac-bundler-0.7.4
    - patch -p1 < ../darktable/packaging/macosx/gtk-mac-bundler-0.7.4.patch
    - make install
    - cd ~/src/darktable/packaging/macosx
    - ./make-app-bundle
